ENV: dev
address: localhost:8080
db_host: localhost
db_port: 5432
db_name: auth_service_db
db_user: postgres
db_password: mysecretpassword
jwt_duration: 1h
server_timeout: 10s
db_max_connections: 100
db_health_check_period: 1m